- name: Check helm version
  set_fact:
    major_helm_version: "{{ helm_version[0] | int }}"
    minor_helm_version: "{{ helm_version[1] | int }}"
- when: major_helm_version | int < 3
  block:
    - name: Check if helm is already initialized
      become_user: "{{service_user}}"
      command: kubectl get pods --namespace kube-system
      changed_when: false
      register: tiller_running
    - name: Add admin cluster role binding for tiller
      template:
        src: tiller-rbac-config.yml
        dest: tiller-rbac-config.yml
    - name: Apply admin cluster role binding for tiller
      become_user: "{{service_user}}"
      command: kubectl create -f tiller-rbac-config.yml
      register: tiller_service_account
      failed_when: false
      changed_when: "'created' in tiller_service_account.stdout"
    - name: Initialize helm
      become_user: "{{service_user}}"
      command: helm init --history-max 200 --service-account tiller
      register: kubernetes_helm_binary_already_exists
      when: "not 'tiller' in tiller_running.stdout"
- name: Update helm repo
  become_user: "{{service_user}}"
  command: helm repo update
  register: update_helm_repos
  changed_when:
    - "'Successfully got an update' in update_helm_repos.stdout"
  failed_when:
    - "update_helm_repos.rc != 0"
    - "'no repositories found. You must add one before updating' not in update_helm_repos.stderr"
- name: Add stable chart repo
  become_user: "{{service_user}}"
  when: helm_add_stable_repo
  kubernetes.core.helm_repository:
    name: stable
    repo_url: "https://charts.helm.sh/stable"
- name: Install helm diff plugin
  when: major_helm_version | int > 2
  command: helm plugin install https://github.com/databus23/helm-diff
  register: helm_diff_plugin
  changed_when:
    - "'plugin already exists' not in helm_diff_plugin.stderr"
  failed_when:
    - "helm_diff_plugin.rc != 0"
    - "'plugin already exists' not in helm_diff_plugin.stderr"
- name: Update helm diff plugin
  command: helm plugin update diff
  register: helm_diff_plugin_update
  changed_when: "'Updated plugin: diff' in helm_diff_plugin_update"
