---
- name: K8s master node configuration
  hosts: k8s-masters
  become: true
  gather_facts: true
  roles:
    - role: common
    # - role: helm
    - role: kubernetes-master
    # - role: istio
    #   when: enable_istio|bool

