---
# Deploys a kubernetes master node
- name: K8s master node configuration
  hosts: k8s-masters
  become: true
  gather_facts: true
  roles:
    - role: common
    - role: kubernetes-master
    - role: helm
    - role: istio
