---
# archive pattern:  https://get.helm.sh/helm-v2.14.1-linux-amd64.tar.gz
# checksum pattern: https://get.helm.sh/helm-v2.14.1-linux-amd64.tar.gz.sha256
helm_mirror: "https://get.helm.sh"
# check newest version here: https://github.com/helm/helm/tags
helm_version: "3.10.3"
helm_platform: "linux-amd64"
helm_archive: "helm-v{{helm_version}}-{{helm_platform}}.tar.gz"
helm_download_url: "{{helm_mirror}}/{{helm_archive}}"
helm_checksum_url: "{{helm_download_url}}.sha256"

helm_bin_dir: "/usr/local/bin"
helm_install_dir: "{{helm_bin_dir}}/helm-v{{helm_version}}"

helm_add_stable_repo: true
