---
- name: "Create {{ flanneld_bin_dir }} directory"
  become: true
  file:
    path: "{{ flanneld_bin_dir }}"
    # owner: "{{service_user}}"
    # group: "{{service_group}}"
    state: directory
    mode: 0755

- name: Check for existing installation of flanneld
  stat:
    path: '{{ flanneld_install }}'
  changed_when: false
  register: flanneld_binary_already_exists

- when: not flanneld_binary_already_exists.stat.exists
  become: true
  block:
    - name: Download flanneld binary
      get_url:
        url: '{{ flanneld_download_url }}'
        dest: '{{ flanneld_install }}'
        # checksum: 'sha256:{{ helm_archive_checksum.content }}'
        mode: 0644

- name: Link the flanneld binary
  become: true
  file:
    src: '{{ flanneld_install }}'
    dest: '{{ flanneld_bin_dir }}/flanneld'
    owner: "{{service_user}}"
    group: "{{service_group}}"
    state: link

# Download and apply manifest
# - name: Download metrics-server manifest to the cluster.
#   ansible.builtin.get_url:
#     url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
#     dest: ~/metrics-server.yaml
#     mode: '0664'

# - name: Apply flannel network fabric manifest
#   kubernetes.core.k8s:
#     state: present
#     src: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

# ~/metrics-server.yaml
    # kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    #
# - name: Configure flannel network fabric
#   become_user: "{{service_user}}"
#   command: "{{ item }}"
#   with_items:
#     - kubectl apply -f {{ flannel_manifest_file_rbac }}
#     - kubectl apply -f {{ flannel_manifest_file }}
#   register: flannel_setup_result
#   changed_when: "'created' in flannel_setup_result.stdout"
