---
- name: Set node hostname
  when: "hostname is defined"
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Update all packages to the latest version.
  apt:
    upgrade: yes
    # upgrade: dist
    update_cache: yes

- name: Install required dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - lsb-release
      - gnupg-agent
      - gnupg
      - software-properties-common
      - jq
      - python3
      - python3-pip
      - selinux-utils
      - firewalld
    state: present
    update_cache: yes

- name: Install pip packages on remote for ansible
  pip:
    name:
      - yq
      - pyyaml
      - kubernetes

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable ufw
  service:
    name: ufw
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable ufw
  ufw:
    state: disabled

- name: Set SELinux to permissive
  command: setenforce 0
  register: selinux_permissive
  failed_when: 'selinux_permissive.rc != 0 and "SELinux is disabled" not in selinux_permissive.stderr'

