---
- name: Update all packages to the latest version.
  apt:
    upgrade: dist

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: ['apt-transport-https',
           'ca-certificates',
           'curl',
           'gnupg-agent',
           'software-properties-common',
            'jq']
    state: present
    update_cache: yes
  ignore_errors: true

- name: Remove previous docker versions
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent
    update_cache: true

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes

- name: Install docker and its dependecies
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
    update_cache: yes
  notify:
    - docker status

- name: Creates directory
  file:
    path: /etc/docker
    state: directory

- name: Configure docker daemon
  template:
    src: docker-deamon.json
    dest: /etc/docker/daemon.json
  register: docker_config

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: restarted
    enabled: true
  when: docker_config is changed

- name: Add {{service_user}} user to docker group
  user:
    name: "{{service_user}}"
    group: docker
    append: yes