- name: "Create {{ flanneld_bin_dir }} directory"
  become: true
  file:
    path: "{{ flanneld_bin_dir }}"
    # owner: "{{service_user}}"
    # group: "{{service_group}}"
    state: directory
    mode: 0755
- name: Check for existing installation of flanneld
  stat:
    path: "{{ flanneld_install }}"
  changed_when: false
  register: flanneld_binary_already_exists
- when: not flanneld_binary_already_exists.stat.exists
  become: true
  block:
    - name: Download flanneld binary
      get_url:
        url: "{{ flanneld_download_url }}"
        dest: "{{ flanneld_install }}"
        # checksum: 'sha256:{{ helm_archive_checksum.content }}'
        mode: 0644
- name: Link the flanneld binary
  become: true
  file:
    src: "{{ flanneld_install }}"
    dest: "{{ flanneld_bin_dir }}/flanneld"
    owner: "{{service_user}}"
    group: "{{service_group}}"
    state: link
# Download and apply manifest
# - name: Download metrics-server manifest to the cluster.
#   ansible.builtin.get_url:
#     url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
#     dest: ~/metrics-server.yaml
#     mode: '0664'
