- name: containerd | Copy containerd config file
  template:
    src: config.toml.j2
    dest: "{{ containerd_cfg_dir }}/config.toml"
    # owner: "root"
    mode: 0640
  notify: restart containerd
# Ensure containerd is started and enabled
- name: containerd | Flush handlers
  meta: flush_handlers
- name: containerd | Ensure containerd is started and enabled
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    state: started
