---
- name: Initialize kubernetes master with kubeadm
  command: >
    kubeadm init
    --node-name k8s-master
    --ignore-preflight-errors=all
    --pod-network-cidr={{ kubernetes_pod_network_cidr }}
    --apiserver-advertise-address={{ apiserver_advertise_address }}
    --apiserver-cert-extra-sans={{ apiserver_advertise_address }}
  #--config /etc/default/kubelet
  #--kubernetes-version {{ kubernetes_version_kubeadm }}
  #--ignore-preflight-errors={{ kubernetes_ignore_preflight_errors }}
  #{{ kubernetes_kubeadm_init_extra_opts }}
  register: kubeadmin_init
  when: not kubernetes_already_initialized.stat.exists

- debug: var=kubeadmin_init #.stdout
  when:
    - not kubernetes_already_initialized.stat.exists
    - kubeadmin_init is failed

- name: Create vagrant kube config directory
  become_user: vagrant
  file:
    path: /home/vagrant/.kube
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'

- name: Change kube config permissions
  file:
    path: /etc/kubernetes/admin.conf
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Setup access for vagrant user
  become_user: vagrant
  file:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    state: link
    mode: '0755'

- name: Testing kubectl access
  become_user: vagrant
  shell: "kubectl get nodes -o json | jq '.items | length'"
  register: node_count
  failed_when: node_count.rc != 0
  changed_when: false