# Configures a k8s master node
# - include_tasks: configure-firewall.yml
- include_tasks: initialize-cluster.yml
- include_tasks: configure-flannel.yml
- include_tasks: disable-taint.yml
- include_tasks: configure-dashboard.yml
- include_tasks: prepare-join.yml
- include_tasks: enable-taint.yml
