---
- name: Add chart repositories
  become_user: "{{service_user}}"
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  with_items: &repos
    - name: stable
      url: "https://charts.helm.sh/stable"
    - name: ingress-nginx
      url: "https://kubernetes.github.io/ingress-nginx"
    - name: jetstack
      url: "https://charts.jetstack.io"
