---
- name: Get kubeadm join token from the kubernetes master node
  become_user: "{{service_user}}"
  command: kubeadm token create --print-join-command
  changed_when: false
  register: kubernetes_join_command_result

- debug: var=kubernetes_join_command_result.stdout_lines[0]

- name: Remove existing join command files
  become: false
  local_action:
    module: file
    path: "./temp-join-command"
    state: absent

- name: Copy join command to local file
  when: kubernetes_join_command_result.stdout is defined
  become: false
  local_action:
    module: copy
    content: "{{ kubernetes_join_command_result.stdout_lines[0] }}"
    dest: "./temp-join-command"
