enable_istio: false
enable_helm: true

# /etc/sysctl.d/k8s.conf
# sysctl_file_path: "/etc/sysctl.d/99-sysctl.conf"
sysctl_file_path: "/etc/sysctl.d/k8s.conf"

kubernetes_pod_network_cidr: '10.244.0.0/16'
allow_pods_on_master: true
kubernetes_enable_web_ui: false
service_user: vagrant
service_group: vagrant

flanneld_release: "https://github.com/flannel-io/flannel/releases/download"
# check newest version here: https://github.com/flannel-io/flannel/tags
flanneld_version: "0.20.2"
flanneld_platform: "amd64"
flanneld_binary: "flanneld-{{flanneld_platform}}"
flanneld_download_url: "{{flanneld_release}}/v{{flanneld_version}}/{{flanneld_binary}}"

flanneld_bin_dir: "/opt/bin/"
flanneld_install: "{{flanneld_bin_dir}}/flanneld-{{flanneld_platform}}-v{{flanneld_version}}"

# Flannel config files.
# https://github.com/flannel-io/flannel/releases/download/v0.18.1/flanneld-amd64
# https://github.com/flannel-io/flannel/releases/download/v0.13.0/flanneld-amd64
# flannel_manifest_file_rbac: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
# flannel_manifest_file: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
